config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users
  resources :products do
    resources :comments
  end
  resources :users
	root 'static_pages#landing_page'

  get 'static_pages/landing_page'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cfrailsproject</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% elsif alert %>
      <p id="alert" class="alert alert-danger"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-inverse navbar-fixed-top" roles="navigation">
      <div class="container-fluid" id="nav_container">
        <div class="navbar-brand">
          <a href="/../static_pages/landing_page.html">Bike NYC</a>
        </div><!--end a_velitsy-->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <%= form_tag("/products", method: "get", class:"navbar-form navbar-left", role:"search") do %>
              <%= content_tag(:div, nil, class: "form-group") do %>
                <%= text_field_tag(:q, "", class:"form-control", placeholder:"Search Products", id:"search_field") %>
                <%= submit_tag("Go", class:"btn btn-default") %>
              <% end %>
            <% end %>
            <li><%= link_to "Home", static_pages_landing_page_path %></li>
            <li><%= link_to "Products", products_url %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%= link_to('login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </div><!--nav-->
      </div><!--end nav container-->
    </nav><!-- end navbar -->
    <%= yield %>
    <footer>
    	&copy; 2017 Bike NYC
    </footer>
  </body>
</html>